name: Deploy by Happy Python

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@master
      with:
        host: 188.225.86.62
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY}}
        script: |
          cd /home/Happy_Python_Teach_Workflow
          git pull origin main
          sudo systemctl restart happt.service
